### ISSUE TITLE
 YSI/pawno/include/YSI/y_hooks/impl.inc Line: 1755

### ISSUE THREAD

**Issue by axi92** [Y-Less/YSI#61]
public OnUnoccupiedVehicleUpdate(vehicleid, playerid, passenger_seat, Float:new_x, Float:new_y, Float:new_z)

According to the Wiki some parameters are missing:
Float:vel_x, Float:vel_y, Float:vel_z
http://wiki.sa-mp.com/wiki/OnUnoccupiedVehicleUpdate

**Comment by weboskop** [comment]
This need to be fixed, i can't compile my gamemode if i want to use this function because i get:

error 025: function heading differs from prototype

**Comment by axi92** [comment]
You can use a workaround do you need the vel parameters in your gamemode?
If not so you can remove them it still work im using this temporary solution myself

**Comment by weboskop** [comment]
Yes i need them ... it's for those stupid cleo hacks.

**Comment by Y-Less** [comment]
Southclaw fixed this ages ago, specifically last August!

https://github.com/Y-Less/YSI/commit/f9c74f508432c6324da91f7f908910e4c212856a

You both need to upgrade.
