### ISSUE TITLE
https://github.com/Y-Less/YSI/blob/master/pawno/include/YSI/y_utils.inc#L157

### ISSUE THREAD

**Issue by axi92** [Y-Less/YSI#62]
If you could check if some define is already defined some users would get less errors.

F.e.:
#if !defined FLOAT_NAN
        #define FLOAT_NAN     (Float:0xFFFFFFFF)
#endif

https://github.com/Y-Less/YSI/blob/master/pawno/include/YSI/y_utils.inc#L157

**Comment by oscar-broman** [comment]
If you define `FLOAT_NAN` the exact same way, it will be ok. This woll work, for example:
```pawn
#define FLOAT_NAN                       (Float:0x7FFFFFFF)
#define FLOAT_NAN                       (Float:0x7FFFFFFF)
#define FLOAT_NAN                       (Float:0x7FFFFFFF)
#define FLOAT_NAN                       (Float:0x7FFFFFFF)
#define FLOAT_NAN                       (Float:0x7FFFFFFF)
```

**Comment by axi92** [comment]
Exact means also with the same number of tabs?
Because I have it in the physics.inc like this:
```
#if !defined FLOAT_NAN
        #define FLOAT_NAN     (Float:0xFFFFFFFF)
#endif
```
And in the y_utils.inc it was like this
```
#define FLOAT_NAN     					(Float:0xFFFFFFFF)
```

**Comment by oscar-broman** [comment]
`FLOAT_NAN` is `0x7FFFFFFF` - not `0xFFFFFFFF`.

**Comment by Y-Less** [comment]
Actually, they are both NAN - the sign is ignored.

**Comment by axi92** [comment]
Ok but what can I do now because there is 2 times the define FLOAT_NAN one time in the include from you Y_Less and one time in the physics.inc?
2 Times the define but with different values?...

**Comment by Y-Less** [comment]
Either change the definition in one of them, or include physics.inc second.

**Comment by axi92** [comment]
Ty for your help
