### ISSUE TITLE
y_dialog.inc

### ISSUE THREAD

**Issue by axi92** [Y-Less/YSI#64]
I have this cmd:

```
CMD:settings(playerid, params[])
{
	new liststring[256];
	inline Response(pid, dialogid, response, listitem, string:inputtext[])
	{
		#pragma unused pid, dialogid, response, inputtext
		if(response == 1)
		{
			switch (listitem)
			{
				case 0: PlayerInfo[playerid][blinker]=(PlayerInfo[playerid][blinker] == 1) ? (0) : (1);
				case 1: togping[playerid]=(togping[playerid] == 1) ? (0) : (1);
			}
		}
	}
	new blinkertext[24], togbingtext[24];
	//----------------------------------------	
	if(PlayerInfo[playerid][blinker] == 1) blinkertext = "{00FF00}AN{FFFFFF}";
	else blinkertext = "{FF0000}AUS{FFFFFF}";
	//----------------------------------------	
	if(togping[playerid] == 1) togbingtext = "{00FF00}AN{FFFFFF}";
	else togbingtext = "{FF0000}AUS{FFFFFF}";
	//----------------------------------------	
	format(liststring, sizeof(liststring), "Blinker: %s \nTogBing: %s", blinkertext, togbingtext);
	Dialog_ShowCallback(playerid, using inline Response, DIALOG_STYLE_LIST , "Settungs", liststring, "OK", "Exit");
	// Main function will end here.
	return 1;
}
```
But I have one issues:
When I press OK it gives me an other dialog not from y_dialog
Is there a way to say start with the internal y_dialog id's from 300+

**Comment by Y-Less** [comment]
Looking at that, it shouldn't show anything when you click OK.  y_dialogs has some support for avoiding clashes, but only in that it won't use IDs already in use, it can't know what other IDs you may use in the future.  Just don't mix the two systems, manually allocating IDs sucks!

**Comment by axi92** [comment]
So I can not use y_dialogs and the normal dialogs at the same time?

**Comment by Y-Less** [comment]
Not easily, as there's no way for each one to know which IDs the other has used.

**Comment by axi92** [comment]
Oh ok, I just wanted to try something new but when its that complicated I'll just stay at the old ones xD
Would be too much work to change all Dialogs (aprox. 200)
Ty for your help again =)
