### ISSUE TITLE
y_hook.inc

### ISSUE THREAD

**Issue by axi92** [Y-Less/YSI#65]
I used 2 times
```
hook OnGameModeInit()
{
//some code
return 1;
}
```
and I got this error:
D:\Downloads\BE\workdir\pawno\include\blinker_sys.inc(263) : error 021: symbol already defined: "@yH_GameModeInit4"
D:\Downloads\BE\workdir\pawno\include\blinker_sys.inc(263) : error 021: symbol already defined: "@yH_GameModeInit4"

**Comment by Y-Less** [comment]
You need to re-include y_hooks each time.

**Comment by Southclaw** [comment]
As the documentation says, you need to include y_hooks in each module you intend to use hooks, this generates new function names.

**Comment by Y-Less** [comment]
I think that's a record for YSI issue replies!

**Comment by axi92** [comment]
Ty ok that was new to me =)
